const state={data:null};
const $=s=>document.querySelector(s);
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
const nowTime=()=>new Date().toLocaleTimeString('en-GB',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false}).slice(0,5);
const orderedCinemas=d=>{const priority=['sunrise','chin-chin'];return [...d.cinemas].sort((a,b)=>{const ai=priority.indexOf(a.id),bi=priority.indexOf(b.id);return (ai<0?99:ai)-(bi<0?99:bi)})};
async function init(){const r=await fetch('./data/showtimes.json');state.data=await r.json();populate();render();$('#updated').textContent=`今日資料：${today()} · 現在時間：${nowTime()} · 最後抓取：${state.data.updated_at}`;['cinemaFilter','movieFilter'].forEach(id=>$('#'+id).addEventListener('change',render));$('#resetBtn').onclick=()=>{['cinemaFilter','movieFilter'].forEach(id=>$('#'+id).value='all');render()}}
function addOptions(id,items){const el=$('#'+id);items.forEach(x=>{const o=document.createElement('option');o.value=x.value;o.textContent=x.text;el.appendChild(o)})}
function populate(){const d=state.data,day=today(),ordered=orderedCinemas(d);addOptions('cinemaFilter',ordered.map(x=>({value:x.id,text:x.name})));addOptions('movieFilter',[...new Set(d.showtimes.filter(x=>x.date===day&&x.times.some(t=>t>nowTime())).map(x=>x.movie))].sort().map(x=>({value:x,text:x})))}
function render(){const d=state.data,day=today(),time=nowTime(),cf=$('#cinemaFilter').value,mf=$('#movieFilter').value;const rows=d.showtimes.filter(x=>x.date===day&&(cf==='all'||x.cinema_id===cf)&&(mf==='all'||x.movie===mf)).map(x=>({...x,times:x.times.filter(t=>t>time)})).filter(x=>x.times.length);const cards=orderedCinemas(d).filter(c=>cf==='all'||c.id===cf).map(c=>{const items=rows.filter(x=>x.cinema_id===c.id);return `<article class="card"><h2>${c.name}</h2><div class="meta">今日 ${day} · 現在 ${time}${c.note?` · ${c.note}`:''}</div>${items.length?items.map(x=>`<div class="movie"><div class="movie-title">${x.movie}</div><div class="version">${x.version}</div><div class="times">${x.times.map(t=>`<span class="time">${t}</span>`).join('')}</div></div>`).join(''):d.data_date!==day?'<div class="empty">今日資料更新中，請稍候重新整理</div>':'<div class="empty">目前沒有還來得及觀看的場次</div>'}</article>`});$('#status').textContent=`目前 ${time} · 還來得及觀看：${rows.length} 組 · 顯示 ${cards.length} 家影城`;$('#results').innerHTML=cards.join('')}
init().catch(e=>{$('#status').textContent='資料載入失敗，請用本機伺服器開啟網站。';console.error(e)});
setTimeout(()=>location.reload(),5*60*1000);
