const state={data:null};
const $=s=>document.querySelector(s);
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
async function init(){const r=await fetch('./data/showtimes.json');state.data=await r.json();populate();render();$('#updated').textContent=`今日資料：${today()} · 最後抓取：${state.data.updated_at}`;['cinemaFilter','movieFilter'].forEach(id=>$('#'+id).addEventListener('change',render));$('#resetBtn').onclick=()=>{['cinemaFilter','movieFilter'].forEach(id=>$('#'+id).value='all');render()}}
function addOptions(id,items){const el=$('#'+id);items.forEach(x=>{const o=document.createElement('option');o.value=x;o.textContent=x;el.appendChild(o)})}
function populate(){const d=state.data,day=today();addOptions('cinemaFilter',d.cinemas.map(x=>x.id));d.cinemas.forEach((x,i)=>$('#cinemaFilter').options[i+1].textContent=x.name);addOptions('movieFilter',[...new Set(d.showtimes.filter(x=>x.date===day).map(x=>x.movie))].sort())}
function render(){const d=state.data,day=today(),cf=$('#cinemaFilter').value,mf=$('#movieFilter').value;const rows=d.showtimes.filter(x=>x.date===day&&(cf==='all'||x.cinema_id===cf)&&(mf==='all'||x.movie===mf));const cards=d.cinemas.filter(c=>cf==='all'||c.id===cf).map(c=>{const items=rows.filter(x=>x.cinema_id===c.id);return `<article class="card"><h2>${c.name}</h2><div class="meta">今日 ${day}${c.note?` · ${c.note}`:''}</div>${items.length?items.map(x=>`<div class="movie"><div class="movie-title">${x.movie}</div><div class="version">${x.version}</div><div class="times">${x.times.map(t=>`<span class="time">${t}</span>`).join('')}</div></div>`).join(''):'<div class="empty">今日尚無抓到場次資料</div>'}</article>`});$('#status').textContent=`今日找到 ${rows.length} 組場次 · 顯示 ${cards.length} 家影城`;$('#results').innerHTML=cards.join('')}
init().catch(e=>{$('#status').textContent='資料載入失敗，請用本機伺服器開啟網站。';console.error(e)});
setTimeout(()=>location.reload(),5*60*1000);
